<a href="https://colab.research.google.com/github/JARACH-209/AI-ML_Lab/blob/master/ML_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part 1**

In [3]:
import numpy as np

tenZeroes = np.zeros(10,dtype = int)
tenOnes = np.ones(10,dtype= int)
tenFives = np.ones(10, dtype = int)*5

print(tenZeroes)
print(tenOnes)
print(tenFives)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]

In [5]:
even = np.arange(10,50,2)
print(even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]

In [26]:
rand = np.random.random([3,3])
print(rand)
np.savetxt("randomMatrix.txt",rand)    #to save any into a file

[[3.51206875e-01 6.88201906e-01 9.00855482e-01]
 [4.77229494e-01 9.36941659e-01 4.31551603e-04]
 [5.18404087e-01 5.80816577e-01 7.10710724e-01]]

# **Part** **2**

In [ ]:
import imageio
print(imageAr)         #the image will have a 3D array as it is RGB. Greyscale image will be 2D.
np.savetxt("imageArray.csv",imageArr,delimiter=",")

#this method will not

In [41]:
import PIL as pil
from PIL import ImageOps
import pandas as pd
image = pil.Image.open("image.jpg")
imageArr = np.array(image)
#print(imageArr)         #3D Array

imageGrey = ImageOps.grayscale(image)
imageG = np.asarray(imageGrey)
print(imageG)

df = pd.DataFrame(imageG)
df.head()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]]

   0     1     2     3     4     5     ...  1394  1395  1396  1397  1398  1399
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 1400 columns]

In [42]:
df.to_csv("imageArray.csv")

In [57]:
data = pd.read_csv("/content/imageArray.csv",skiprows=-1)
data.shape
data.drop(data.columns[-1],axis=1,inplace =True)
data.shape

(700, 1400)

In [61]:
from datetime import date
today = pd.to_datetime(str(date.today()),format="%Y-%m-%d")
print(today)

2020-08-22 00:00:00

# **Part 3**

In [65]:
from datetime import date
today = date.today()
inp = input("Enter the date in formate YYYY MM DD").split(" ")
bday = date(int(inp[0]),int(inp[1]),int(inp[2]))
age = today.year - bday.year - ((today.month, today.day) < (bday.month, bday.day))
print("Age of the person is ",age)

Enter the date in formate YYYY MM DD1973 06 15
Age of the person is  47